### ISSUE TITLE
Improve the Styleguide

### ISSUE THREAD

**Issue by Kriesse** [co-up/co-up.de#10]
The current styleguide could be extended to be more helpful, e.g. with some basic rules for writing, tone and voice, how to spell "co.up", etc. 

Current status:
https://co-up.de/styleguide/

**Comment by saebender** [comment]
I started on this, I added two sections that we can place above the existing content. Looking for feedback @Kriesse @CobotClaire because I'm not as familiar with co.up style as you are.

Draft text:

## Spelling/punctuation

co.up is all lowercase, and is defined by the "." in between "co" and "up." co.up is lowercase even when it starts a sentence.

**This creates problems with certain functions (like web addresses, hashtags, etc.).** When you can't use co.up:

If possible, default to using a "-" instead of "."

> Example: *www.co-up.de*

If that is not possible (for example, in a hashtag), co.up should be written as CoUp, so as to separate it from the word coup. 

> Example: Our #saveCoUp campaign.

## Tone

The co.up style is extremely familiar and personable. In writing, co.up will often use all lowercase when talking directly to people, and frequently uses emojis, common slang, and display an insiders knowledge of tech vocabulary.

co.up is **community-focused** above all else. We support the independence of the organizers and organizations that use our space, and we don't want to be involved in their operations or content. However, co.up is also very deeply concerned about accessibility, inclusion, and representation, so we take a strong stance against anything within co.up  or around co.up that goes against the values outlined in our [code of conduct](https://co-up.de/code-of-conduct/).

**Comment by CobotClaire** [comment]
This all looks correct to me! I would put https://co-up.de instead of www.co-up.de

For tone, I would add that we strive to use language that is inclusive - for example, using non-gendered terms (e.g. "folks", "y'all") - and that also follows our CoC (which sounds obvious perhaps, but we should explicitly state here that it also applies to us.

**Comment by saebender** [comment]
Good idea! Here's an updated draft of the new text:

## Spelling/punctuation

co.up is all lowercase, and is defined by the "." in between "co" and "up." co.up is lowercase even when it starts a sentence.

**This creates problems with certain functions (like web addresses, hashtags, etc.).** When you can't use co.up:

If possible, default to using a "-" instead of "."

> Example: [https://co-up.de](https://co-up.de/)

If that is not possible (for example, in a hashtag), co.up should be written as CoUp, so as to separate it from the word coup. 

> Example: Please check out our #saveCoUp campaign

## Inclusive Language

co.up avoids gendered words and phrases (like referring to a group as "guys") and always uses non-gendered terms (such as you all, everyone, folks, etc.). 

> Example: We're looking forward to seeing folks at the event later!

Please refer to our [code of conduct](https://co-up.de/code-of-conduct/) if you have any questions about what we mean by inclusive language.

## Tone

The co.up style is extremely familiar and personable. In writing, co.up will often use all lowercase when talking directly to people, and frequently uses emojis, common slang, and display an insiders knowledge of tech vocabulary.

co.up is **community-focused** above all else. We support the independence of the organizers and organizations that use our space, and we don't want to be involved in their operations or content. However, co.up is also very deeply concerned about accessibility, inclusion, and representation, so we take a strong stance against anything within co.up  or around co.up that goes against the values outlined in our [code of conduct](https://co-up.de/code-of-conduct/).

**Comment by CobotClaire** [comment]
Looks good to me!

**Comment by CobotClaire** [comment]
Added updating this page to my to-do list.

**Comment by CobotClaire** [comment]
Added the copy to the page -- formatting could probably use some tweaking. @Kriesse @saebender what do you think? https://co-up.de/styleguide/
