### ISSUE TITLE
Create blogpost about info evening

### ISSUE THREAD

**Issue by Kriesse** [co-up/co-up.de#2]
Let's collect the outcome of the info evening on November 19 and share it in a blogpost.

- [x] write post (@saebender)
- [ ] add a blog post .md file 
- [ ] add text and transform into markup

**Comment by saebender** [comment]
Draft post: 
**Thanks to everyone who showed up to our #saveCoUp info evening yesterday!** For those of you who couldn't make it, we've got a recap so you can follow along in our discussion.

First, some details. Around 40 people attended, about half of which were event organizers and the other half were participants, interested groups, or potential company supporters. **You can find the complete event from our recorded livestream on the [co.up Facebook page](https://www.facebook.com/co.up.community/).**

Here is a summary of the evening based on our notes:

### Lightning talks (with livestream timecodes)

- Charlie Owen: Why co.up must stay (14:50)
- Martin Meyerhoff: How to donate and use no-profit structures (19:15)
- Bastian Albers: OpenTechSchool <3 co.up ([https://slides.com/bastianalbers/opentechschool-co_up/fullscreen](https://slides.com/bastianalbers/opentechschool-co_up/fullscreen)) (24:47)
- Florian Gilcher: Why independence is important for community meetups (34:42)
- Robin Mehner: The story of BerlinJS and co.up (42:24)

### Join our slack and keep the discussion going

We have a Slack channel to strategize and work together on the campaign, this will be the central point of discussion for #saveCoUp. **Send us an email at hello@co-up.de if you'd like to join**.

### Ideas from the discussion

- Run an event for code learners to meet hiring companies, companies have to pay to attend.
- Set up a referral program where companies that hire co.up "alumni" would pay a hiring fee.
- Special event: BerlinJS meets [Upfront.ug](http://upfront.ug) (tentative date December 11th), where optional tickets will be sold
- [Upfront.ug](http://upfront.ug) shared a template for how to offer a sponsored announcement at a meetup and send the money to co.up [http://up.front.ug/sponsoring/](http://up.front.ug/sponsoring/)
- For those without money or reach, there are still options. Reach out to your networks, talk to your company, and help us organize on our Slack channel or GitHub.
- Our plan to get more companies on board is to strategically reach out to members who might be able to convince their employers. This will be a community effort since so much of it is out of our hands, but we do have a guide for anyone interested in talking to their boss.
- We are willing to work with companies to find ways to offer benefits, but we're unwilling to do anything that would force meetup organizers to show preference, read from scripts, or require effort towards a sponsor. We also want to keep our space as free of logos and corporations as possible.
- There are some potential sponsorship opportunities:
    - HR agencies
    - Innovation labs
    - Other similar communities/orgs to co.up's that we can network with (in Germany and abroad)
- If people want to make cryptocurrency-based contributions, it must all be 100% legal. Since we're unable to do the necessary work to make sure of that, we're going to avoid this for the time being.
- Some community suggestions:
    - Recruiting event yearly or biannual
    - Jobseekers pledge that the company that hires them donate to co.up
    - Sponsorship link for companies to sponsor an event and thereby co.up
    - Sponsorship slot on the upfront model
    - Organizations can present a sponsor at their meetup
    - Emphasize the healthy environment where you can hire prople
    - People who do consultancy here can donate part of their income to the space
    - Job board on the website of co.up where companies have to pay for an entry
    - Help orgs to communicate the costs associated with coming here to the attendees (add this to the materials—this is what you’re not paying for when you come here!)
    - Progress bar on the jar?
    - Give Robin / orgs a slide with a number for the campaign
    - Help people with the website — join the Slack and repo so we can all work together
    - Tweet the slack!
    - Sponsorship packages
    - Lottery tickets for consultancy hours with people at the meetups
- Suggestions tweeted by Wizard Amigos: [https://twitter.com/wizardamigos/status/1196878443754819584](https://twitter.com/wizardamigos/status/1196878443754819584)
- Suggestion from a visitor from Saftladen (our next-door neighbour games studio):
    - Maybe games and tech can join forces and pay a person for a certain amount of time to found a Verein or similar

### What's next?

We'll continue to post more resources over the upcoming weeks, and if you're wondering how you can help, send us a request to join the slack group! That will be where we bring the latest news about the campain, the strategy, and ways that we can keep co.up's doors open. 

Looking forward to working together!

**Comment by Kriesse** [comment]
Done – It's now live here: https://co-up.de/2019/11/21/save-coup-info-evening-recap/
