### ISSUE TITLE
Update what we offer for company support membership on the related pages

### ISSUE THREAD

**Issue by CobotClaire** [co-up/co-up.de#23]
We've gotten some feedback I propose we integrate, including but not limited to:

- [x] possibility of a large one-time yearly sponsorship (instead of monthly support), which might fit it better for budget reasons in some companies
- [x] higher space rental discount (see #20)
- [x] offering a way to recruit or benefit from know-how in the space (see info evening ideas summary: https://co-up.de/2019/11/21/save-coup-info-evening-recap/): biannual job fair, announcement of a company's recruitment event
- [x] not referring to it as a donation anywhere (removes confusion for tax purposes) but sponsorship or partnership
- [x] mention the stickers table (placing flyers and stickers)
- [x] partnership possibility: offering exclusive packages (which you only get via co.up)
- [x] add more info on what kind of events are in the space, how many people are there every week, and how many people are reached via blogpost/Twitter/Facebook/Insta.
- [ ] link to the pages on the website

Can we work on having this live next week? I would pre-announce some changes in a Twitter thread tomorrow. cc @Kriesse @saebender

**Comment by thilo** [comment]
@CobotClaire I created sponsorship plans and also cleaned up old plans https://members.co-up.de/admin/plans

**Comment by saebender** [comment]
@CobotClaire I made a new draft of the /sponsorships page incorporating some of the feedback we've received:

Interested in becoming one of co.up's supporting companies?

### Why your support matters

co.up is a community event space—but it’s so much more than that. It’s a place where the next generation of developers, designers, innovators and entrepreneurs are honing their craft right now; it's a place where your financial background doesn’t determine the level of support you receive; and it’s part of the spirit of the Berlin tech scene. 

For 10 years, co.up has provided free tech education to thousands of attendees across thousands of meetups, workshops, and learning groups. co.up kicked off the creative tech scene in Berlin when there was no infrastructure to train tech talent, no places to meet and collaborate, no places that were open and inclusive. It is safe to say that co.up has shaped a big part of the current technical work force in Berlin, and spawned many huge and influential communities in Berlin, e.g. the CSSconf and JSconf events, the OpenTechSchool movement, and more.

Now you have the chance to be a part of co.up's next chapter, providing an affordable space to organizations fighting to make tech more representative.

We need to raise 3000€ in monthly contributions in order to maintain co.up and our mission. Your company contribution will make an enormous difference in whether co.up can stay affordable and open to the community for events, learning groups, workshops, and more.

### How can you sponsor co.up?

You help us most by committing to a recurring monthly contribution of at least EUR 200 (link).

Alternatively, you can make a 1-time contribution of at least EUR 500 (link).

### What we offer

We estimate that between 20-50.000 people have come through co.up over the years, over an estimated 3000 events, and every month we currently get around 500 visitors. This is an opportunity for you to not only support the organizations in the space, but make yourself visible to the countless future talent that is currently developing their skills in our space.

**These numbers are conservative best guesses, based on our calendar of the last ten years, and average visitor numbers that meetups report to us. We don’t track the exact number of visitors in the space.*

All of our company supporters get the following: 

- Your name, logo and link displayed on our website.
- A notice of thanks in the space itself, including your company name and logo.
- One thank-you tweet and one Facebook post.
- A mention in our blog.

If you commit to a recurring membership of more than EUR 300, or contribute more than EUR 1500 at once, in addition to the benefits listed above, you'll get the following:

- A 25% discount on renting the space for private company events (with a further discount on recurring events).
- A monthly thank-you tweet and Facebook post.
- A dedicated blog post about your company, e.g. your hiring goals or community work in Berlin (text provided by you).
- Opportunities for recruitment benefits (We do not allow recruiters into the space regularly, but we are working on ways to connect interested applicants with our company supporters)

We're looking into more ways to thank our supporting companies. If your organization has a request, e.g. ideas about how co.up can support you in hiring, recruiting, or your education needs, please reach out to us and we can discuss ways that we can work together.

### What we can’t offer

Please note: co.up will not collect and provide our attendees or organizers' personal data, nor will we demand from our communities to follow any marketing obligations. All events at co.up are run under a [Code of Conduct](https://co-up.de/code-of-conduct/) and must be free, open, and with a visible effort to be safe, inclusive and welcoming.

### How to contribute

If you want to become a company supporter or have questions we can answer, please email hello@co-up.de explaining your situation. You can also visit [members.co-up.de](http://members.co-up.de) and choose one of the preselected options.

### Thank you for your support!

**Comment by CobotClaire** [comment]
Thx! My feedback on this @saebender:

- [ ] can we add a link to the list of the groups meeting here, somewhere? https://co-up.de/events/
- [ ] can we use the word "sponsorship" a bit more, or would that be too much?
- [ ] can we also edit the "talk to your employer" page to reflect these changes?

**Comment by thilo** [comment]
@CobotClaire here example of the yearly options linked. 
https://members.co-up.de/membership_signup/new?plan_id=b7cc0e80af703e64643e0d1e5c652751

Only graphic for 400 EUR is missing. (@Kriesse)

**Comment by saebender** [comment]
Next draft with edits for @CobotClaire 
### Why your support matters

co.up is a community event space—but it’s so much more than that. It’s a place where the next generation of developers, designers, innovators and entrepreneurs are honing their craft right now; it's a place where your financial background doesn’t determine the level of support you receive; and it’s part of the spirit of the Berlin tech scene. 

For 10 years, co.up has provided free tech education to thousands of attendees across thousands of meetups, workshops, and learning groups. co.up kicked off the creative tech scene in Berlin when there was no infrastructure to train tech talent, no places to meet and collaborate, no places that were open and inclusive. It is safe to say that co.up has shaped a big part of the current technical work force in Berlin, and spawned many huge and influential communities in Berlin, e.g. the CSSconf and JSconf events, the OpenTechSchool movement, and more.

Find a complete list of the events that take place in the space here: [https://co-up.de/events/](https://co-up.de/events/)

**Now you have the chance to be a part of co.up's next chapter by becoming a co.up sponsor.** Your contribution will directly help provide an affordable space to organizations fighting to make tech more representative.

We need to raise 3000€ in monthly contributions in order to maintain co.up and our mission. Your company contribution will make an enormous difference in whether co.up can stay affordable and open to the community for events, learning groups, workshops, and more.

### How can you sponsor co.up?

You help us most by committing to a recurring monthly contribution of at least EUR 200 (link).

Alternatively, you can make a 1-time contribution of at least EUR 500 (link).

### What we offer

We estimate that between 20-50.000 people have come through co.up over the years, over an estimated 3000 events, and every month we currently get around 500 visitors. This is an opportunity for you to not only support the organizations in the space, but make yourself visible to the countless future talent that is currently developing their skills in our space.

**These numbers are conservative best guesses, based on our calendar of the last ten years, and average visitor numbers that meetups report to us. We don’t track the exact number of visitors in the space.*

All of our company supporters get the following: 

- Your name, logo and link displayed on our website.
- A notice of thanks in the space itself, including your company name and logo.
- One thank-you tweet and one Facebook post.
- A mention in our blog.

If you commit to a recurring membership of more than EUR 300, or contribute more than EUR 1500 at once, in addition to the benefits listed above, you'll get the following:

- A 25% discount on renting the space for private company events (with a further discount on recurring events).
- A monthly thank-you tweet and Facebook post.
- A dedicated blog post about your company, e.g. your hiring goals or community work in Berlin (text provided by you).
- Opportunities for recruitment benefits (We do not allow recruiters into the space regularly, but we are working on ways to connect interested applicants with our company supporters)

We're looking into more ways to thank our supporting companies. If your organization has a request, e.g. ideas about how co.up can support you in hiring, recruiting, or your education needs, please reach out to us and we can discuss ways that we can work together.

### What we can’t offer

Please note: co.up will not collect and provide our attendees or organizers' personal data, nor will we demand from our communities to follow any marketing obligations. All events at co.up are run under a [Code of Conduct](https://co-up.de/code-of-conduct/) and must be free, open, and with a visible effort to be safe, inclusive and welcoming.

### How to contribute

If you want to become a company supporter or have questions we can answer, please email hello@co-up.de explaining your situation. You can also visit [members.co-up.de](http://members.co-up.de) and choose one of the preselected options.

### Thank you for your support!

**Comment by saebender** [comment]
And for the

**Comment by saebender** [comment]
And the new text draft for https://co-up.de/convince-your-company-to-support-coup/

## How to Get Your Company to Support co.up

For co.up to survive, it's going to take recurring support, and while every contribution is essential, our success will depend on getting a few company supporters capable of contributing larger amounts. But how do you get your organization/employer to become a supporter? Here are some steps you can take to start the conversation and turn your company into a co.up supporter.

### You were hired there, tell them your co.up story!

Nothing beats a personal connection. Open your conversation by speaking about how important co.up was in your history and where you think you'd be without it. Was your first meetup here? Did you make any important connections? Would that have been possible without a free community space like co.up? 

Your employer might not know how much co.up is contributing to skills development in its employees—they might not know about co.up at all! If that's the case, give them a brief overview; tell them that it's a community space that offers free event space for public organizations working to make tech more representative in Berlin.

### You get benefits, too!

co.up is filling knowledge gaps. Your company's employees get access to free knowledge-sharing which can range anywhere from talks at meetups to workshops and co-learning; these all help them to become better, well-rounded and knowledgeable employees. Most of these events are made possible by the access co.up provides to free and regularly available event space.

Do you currently go to a meetup, learning group, or other event in co.up? If so, your company is already benefiting from co.up! Emphasize what you've gotten out of your experience in the space and how it's been developing your skills and networks, and how the company will lose that resource in your life and others' if co.up doesn't get company support. The monthly cost for your company is probably less than paying for your professional development outside of co.up!

### What co.up offers

Your company's logo will be prominently placed on our website and in the space, both of which are regularly seen by tech workers and talent in Berlin.

You'll receive a shot out on our social media, as well as a mention in our blog.

If your company commits to a recurring membership of more than EUR 300, or a one-time contribution of EUR 1500 at once, in addition to the other benefits, you'll get the following:

Your company will get access to our event space for private events at a 25% discount, which they can use for company off-sites, events, or other closed functions. 

A dedicated post on our blog about your company (text provided by you)

We're also working on a way to match recruiters with interested applicants at events in the space that should be premiered early next year.

### Support the tech environment that supports you

Supporting co.up means supporting an organization that makes the Berlin tech scene extremely valuable for prospective employees from outside of Berlin. In a competitive job market, saying that you support the local tech scene is a great pitch for why a prospective employee should decide to work for you. 

Here are just a few of the events that operate in the space:

berlin.JS

OpenTechSchool

bePHPug

Supporting the community reassures people that your company cares about the tech community and the personal career development of its employees.

### Direct them to our company supporters webpage

We go over all of the reasons for becoming a company supporter here: [https://co-up.de/sponsorships/](https://co-up.de/sponsorships/)

You can also put them in touch with our team directly using the email hello@co-up.de

### What to do if they say no?

Don't panic! You might hear a few different things:

- "We only support non-profits."
    - What to say: "Think about it as paying for my professional development." It's difficult to get around this one—there might be company policy that prevents it as a whole. However, if your company pays for remote workers' coworking space memberships, professional development, or other employee perks, try and emphasize the functionality of co.up to you and others. It's a bargain at that price!
- "Why don't we get more for supporting them?"
    - What to say: "You get so much! It's just intangible." Companies love to talk about soft skills: this is a soft skill for your business. Think about how much you pay for marketing campaigns to convince hip Berliners to use your product. Now think about how much cheaper it would be to support co.up and talk about that support. It's instant street cred!
- "Recurring monthly membership? Why can't we just make a big contribution?"
    - What to say: "Without recurring support, it's a gamble for co.up to sign their lease and they're not in a financial position to make that gamble." This is just the truth: we need recurring support. One-time contributions are accepted and celebrated, but if we don't meet our recurring goal, then we can't sign the new lease.

### Thank you for talking to your employer! Let's go #saveCoUp.

**Comment by thilo** [comment]
@saebender I added some comments on the why sponsor doc as we have more detailed info about sponsoring: https://www.notion.so/cobotme/Why-Support-as-a-Company-Page-82efef883a8a474fac674bdb279915be

**Comment by saebender** [comment]
@thilo @CobotClaire I made the edits in Notion and have a draft for you both to review. The only change that I wasn't able to apply is adding the buttons to the "How can you sponsor co.up?" section.

Interested in becoming one of co.up's supporting companies?

### Why your support matters

co.up is a community event space—but it’s so much more than that. It’s a place where the next generation of developers, designers, innovators and entrepreneurs are honing their craft right now; it's a place where your financial background doesn’t determine the level of support you receive; and it’s part of the spirit of the Berlin tech scene. 

For 10 years, co.up has provided free tech education to thousands of attendees across thousands of meetups, workshops, and learning groups. co.up kicked off the creative tech scene in Berlin when there was no infrastructure to train tech talent, no places to meet and collaborate, no places that were open and inclusive. It is safe to say that co.up has shaped a big part of the current technical work force in Berlin, and spawned many huge and influential communities in Berlin, e.g. the CSSconf and JSconf events, the OpenTechSchool movement, and more.

Find a complete list of the events that take place in the space here: [https://co-up.de/events/](https://co-up.de/events/)

**Now you have the chance to be a part of co.up's next chapter by becoming a co.up sponsor.** Your contribution will directly help provide an affordable space to organizations fighting to make tech more representative.

**We need to raise 3000€ in monthly contributions by January 1st, 2020** in order to maintain co.up and our mission. Your company contribution will make an enormous difference in whether co.up can stay affordable and open to the community for events, learning groups, workshops, and more.

### How can you sponsor co.up?

You help us most by committing to a recurring [monthly contribution of at least EUR 200](https://members.co-up.de/).

Alternatively, you can make a [one-time contribution of at least EUR 500](https://members.co-up.de/).

Note: This option can be used via "yearly payment" membership, which may be cancelled immediately to limit your support to a one-time payment.

### What we offer

We estimate that between 20-50.000 people have come through co.up over the years, over an estimated 3000 events, and every month we currently get around 500 visitors. This is an opportunity for you to not only support the organizations in the space, but make yourself visible to the countless future talent that is currently developing their skills in our space.

**These numbers are conservative best guesses, based on our calendar of the last ten years, and average visitor numbers that meetups report to us. We don’t track the exact number of visitors in the space.*

All of our company supporters get the following: 

- Your name, logo and link displayed on our website.
- A notice of thanks in the space itself, including your company name and logo.
- One thank-you tweet and one Facebook post.
- A mention in our blog.

If you commit to a recurring membership of more than EUR 300, or contribute more than EUR 1500 at once, in addition to the benefits listed above, you'll get the following:

- A 25% discount on renting the space for private company events (with a further discount on recurring events).
- A monthly thank-you tweet and Facebook post.
- A dedicated blog post about your company, e.g. your hiring goals or community work in Berlin (text provided by you).
- Opportunities for recruitment benefits (We do not allow recruiters into the space regularly, but we are working on ways to connect interested applicants with our company supporters)

We're looking into more ways to thank our supporting companies. If your organization has a request, e.g. ideas about how co.up can support you in hiring, recruiting, or your education needs, please reach out to us and we can discuss ways that we can work together.

### What we can’t offer

Please note: co.up will not collect and provide our attendees or organizers' personal data, nor will we demand from our communities to follow any marketing obligations. All events at co.up are run under a [Code of Conduct](https://co-up.de/code-of-conduct/) and public events (events for which you don’t pay rent) must be free, open, and with a visible effort to be safe, inclusive and welcoming.

As co.up is not a registered non-profit, donations are not tax-deductible and we are unable to produce Spendenquittungen. We are, however, working on changing this.

### How to contribute

If you want to become a company supporter or have questions we can answer, please email hello@co-up.de explaining your situation. You can also visit [members.co-up.de](http://members.co-up.de) and choose one of the preselected options.

### Thank you for your support!

**Comment by saebender** [comment]
Latest draft, changed the final date and added a note about the buttons.

Interested in becoming one of co.up's supporting companies?

### Why your support matters

co.up is a community event space—but it’s so much more than that. It’s a place where the next generation of developers, designers, innovators and entrepreneurs are honing their craft right now; it's a place where your financial background doesn’t determine the level of support you receive; and it’s part of the spirit of the Berlin tech scene. 

For 10 years, co.up has provided free tech education to thousands of attendees across thousands of meetups, workshops, and learning groups. co.up kicked off the creative tech scene in Berlin when there was no infrastructure to train tech talent, no places to meet and collaborate, no places that were open and inclusive. It is safe to say that co.up has shaped a big part of the current technical work force in Berlin, and spawned many huge and influential communities in Berlin, e.g. the CSSconf and JSconf events, the OpenTechSchool movement, and more.

Find a complete list of the events that take place in the space here: [https://co-up.de/events/](https://co-up.de/events/)

**Now you have the chance to be a part of co.up's next chapter by becoming a co.up sponsor.** Your contribution will directly help provide an affordable space to organizations fighting to make tech more representative.

**We need to raise 3000€ in monthly contributions by January 10th, 2020** in order to maintain co.up and our mission. Your company contribution will make an enormous difference in whether co.up can stay affordable and open to the community for events, learning groups, workshops, and more.

### How can you sponsor co.up?

You help us most by committing to a recurring [monthly contribution of at least EUR 200](https://members.co-up.de/).

Alternatively, you can make a [one-time contribution of at least EUR 500](https://members.co-up.de/).

Note: This option can be used via "yearly payment" membership, which may be cancelled immediately to limit your support to a one-time payment.

[NOTE: please add buttons for these options]

### What we offer

We estimate that between 20-50.000 people have come through co.up over the years, over an estimated 3000 events, and every month we currently get around 500 visitors. This is an opportunity for you to not only support the organizations in the space, but make yourself visible to the countless future talent that is currently developing their skills in our space.

**These numbers are conservative best guesses, based on our calendar of the last ten years, and average visitor numbers that meetups report to us. We don’t track the exact number of visitors in the space.*

All of our company supporters get the following: 

- Your name, logo and link displayed on our website.
- A notice of thanks in the space itself, including your company name and logo.
- One thank-you tweet and one Facebook post.
- A mention in our blog.

If you commit to a recurring membership of more than EUR 300, or contribute more than EUR 1500 at once, in addition to the benefits listed above, you'll get the following:

- A 25% discount on renting the space for private company events (with a further discount on recurring events).
- A monthly thank-you tweet and Facebook post.
- A dedicated blog post about your company, e.g. your hiring goals or community work in Berlin (text provided by you).
- Opportunities for recruitment benefits (We do not allow recruiters into the space regularly, but we are working on ways to connect interested applicants with our company supporters)

We're looking into more ways to thank our supporting companies. If your organization has a request, e.g. ideas about how co.up can support you in hiring, recruiting, or your education needs, please reach out to us and we can discuss ways that we can work together.

### What we can’t offer

Please note: co.up will not collect and provide our attendees or organizers' personal data, nor will we demand from our communities to follow any marketing obligations. All events at co.up are run under a [Code of Conduct](https://co-up.de/code-of-conduct/) and public events (events for which you don’t pay rent) must be free, open, and with a visible effort to be safe, inclusive and welcoming.

### How to contribute

If you want to become a company supporter or have questions we can answer, please email hello@co-up.de explaining your situation. You can also visit [members.co-up.de](http://members.co-up.de) and choose one of the preselected options.

### Thank you for your support!

**Comment by CobotClaire** [comment]
@Kriesse @carmem-s we would need buttons for this post (see above)

**Comment by saebender** [comment]
Here's a link to the most updated draft within Notion:
https://www.notion.so/cobotme/Why-Support-as-a-Company-Page-82efef883a8a474fac674bdb279915be

**Comment by Kriesse** [comment]
done!
